### ISSUE TITLE
React compatibility

### ISSUE THREAD

**Issue by lazorfuzz** [Cristian006/frameless-titlebar#16]
Can this only work with 16.6.3 or up? Or can people with earlier React versions use this? If so I'd recommend changing the React version in package.json for developers who, for legacy reasons or otherwise, cannot upgrade their version of React.

**Comment by Cristian006** [comment]
@lazorfuzz Right now the lowest supported version is v16.6.0 but I will work on removing the need for the context api and pass the theme properties via component props to support older versions of react.

**Comment by Cristian006** [comment]
@lazorfuzz working on removing context api requirement in fac31f66673323b569fd6996422b67029501c555 to lower required react version from v16.6.x to v15.x.x
