### ISSUE TITLE
Bug: shortcuts not displayed correctly in menus

### ISSUE THREAD

**Issue by erikjalevik** [Cristian006/frameless-titlebar#23]
If specifying accelerators in a menu template using the cross-platform syntax, i.e.

`accelerator: "CmdOrCtrl+Z"`

these strings get printed verbatim in the menus. However, in the native menus, they get translated to the appropriate shortcut for the platform, i.e. for Windows:

`Ctrl+Z`

And for Mac:

`⌘Z`

**Comment by Cristian006** [comment]
Accelerator parsing support for "CmdOrCtrl" as well as "CommandOrControl". Currently only replacing "CommandOrControl" to its respective platform representation.
