### ISSUE TITLE
importing the package throws `fs.existsSync` is not a function.

### ISSUE THREAD

**Issue by J-Cake** [Cristian006/frameless-titlebar#27]
So I haven't done anything, no configuration, not even use the Component - just import the package, and i get an error from React saying `fs.existsSync` does not exist. And it points to electron's install script!

    TypeError: fs.existsSync is not a function
    C:/path/to/react/and/electron/project/node_modules/electron/index.js:8

Everything is up to date, including windows, and I have no Idea what's wrong!

**Comment by danielkv** [comment]
Having the same problem

**Comment by Cristian006** [comment]
@danielkv fixed in new update
