### ISSUE TITLE
title bar not showing

### ISSUE THREAD

**Issue by tamimmirza** [Cristian006/frameless-titlebar#32]
I have installed node.js and electron (all latest versions) and then I installed your frameless titlebar

But the project did not contain a "renderer" file so I created a `renderer.js` and added the portion:

```
import TitleBar from 'frameless-titlebar';
import menu from './AppMenu';

    export default class App extends React.Component
    {
        render()
        {
            return (
      <div>
        <TitleBar
          icon={codeIcon}
          app="Code"
          title="index.js - frameless-titlebar"
          menu={defaultTemplate}
          theme={{
            barTheme: 'dark',
            barBackgroundColor: 'rgb(36, 37, 38)',
            barColor: 'rgb(230, 230, 230)',
            menuHighlightColor: '#373277',
            menuDimItems: false,
            showIconDarLin: false
          }}
        />
      </div>
    );
        }
    }
```

How ever despite this the title bar still did not load and I have followed the instructions to set the browserwindow frame component to false.  As in your documentation, my app does net yet have a native root container and therefore the app crashes when I put this block of code in my mainWIndow.js

Perhaps I need guidance on what I have done wrong and how to get back on the right track. I am a beginner to electron and node.js

**Comment by Cristian006** [comment]
Have a look at the [example project](https://github.com/Cristian006/frameless-titlebar/tree/master/example) to see how to setup a simple React + Electron app.

Here is a pretty solid boilerplate electron + react boilerplate: https://github.com/electron-react-boilerplate/electron-react-boilerplate
