### ISSUE TITLE
Should display menu on Linux

### ISSUE THREAD

**Issue by hemancuso** [Cristian006/frameless-titlebar#33]
According to the docs, the menu should display on Linux. Currently only win32 gets that treatment. Perhaps this is desired, but should be configurable.

**Comment by dit-j** [comment]
The same issue on mac. I should have tested this at the very beginning of our current project ... :(

**Comment by Cristian006** [comment]
@dit-j you want the menu to display on Mac?

**Comment by Cristian006** [comment]
@hemancuso I will add this in as a configurable property for both Mac and Linux 👌

**Comment by Cristian006** [comment]
@hemancuso menus are now displayed on linux 👍 checkout the demo https://cristian006.github.io/frameless-titlebar/
