### ISSUE TITLE
Got error while starting example - Module build failed: Error: Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by dit-j** [Cristian006/frameless-titlebar#35]
Here is the error log:

> yarn run v1.13.0
> $ webpack-dev-server --hot --host 0.0.0.0 --config=./webpack.dev.config.js
> The `setup` option is deprecated and will be removed in v3. Please update your config to use `before`
> Project is running at http://0.0.0.0:8080/
> webpack output is served from /
> Content not from webpack is served from D:\workspaces-test\frameless-titlebar-master\example\dist
> 
> Hash: 1caf05bacc4337ba547c
> Version: webpack 3.12.0
> Time: 861ms
>         Asset       Size  Chunks                    Chunk Names
>     bundle.js     301 kB       0  [emitted]  [big]  main
> bundle.js.map     347 kB       0  [emitted]         main
>    index.html  183 bytes          [emitted]
>    [0] (webpack)/hot/log.js 1.04 kB {0} [built]
>    [2] (webpack)/hot/emitter.js 77 bytes {0} [built]
>    [3] multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/index.js 52 bytes {0} [built]
>    [4] (webpack)-dev-server/client?http://0.0.0.0:8080 7.93 kB {0} [built]
>    [5] external "url" 42 bytes {0} [not cacheable]
>    [6] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
>    [8] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} [built]
>    [9] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
>   [11] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
>   [12] ./node_modules/ansi-html/index.js 4.26 kB {0} [built]
>   [13] ./node_modules/html-entities/index.js 231 bytes {0} [built]
>   [16] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
>   [18] (webpack)/hot/dev-server.js 1.61 kB {0} [built]
>   [19] (webpack)/hot/log-apply-result.js 1.31 kB {0} [built]
>   [20] ./src/index.js 1.64 kB {0} [not cacheable] [built] [failed] [1 error]
>     + 6 hidden modules
> 
> ERROR in ./src/index.js
> Module build failed: Error: Cannot find module '@babel/core'
>  babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)

**Comment by Cristian006** [comment]
Did you follow https://github.com/Cristian006/frameless-titlebar#try-the-example and yarn install the dependancies in both the root directory of frameless-titlebar and the example directory?

**Comment by dit-j** [comment]
thy for your reply. It works now. 

So I can not use the /example as a template ? 
How should I change the /example project to run it without root directory?

regards
dit

**Comment by Cristian006** [comment]
I recommend using something like https://github.com/electron-react-boilerplate/electron-react-boilerplate since the example was just meant to showcase the titlebar, not necessarily meant as a project boilerplate. To answer your question though, if you go into the example folder and delete [line #41](https://github.com/Cristian006/frameless-titlebar/blob/master/example/package.json#L41) from `package.json` that will remove the outer folder as a project dependency. Then run `yarn add frameless-titlebar` to install frameless-titlebar as a regular node module 👍
