### ISSUE TITLE
can i install with npm?

### ISSUE THREAD

**Issue by omerfeyyaz** [Cristian006/frameless-titlebar#5]
can i install with npm?
I like this, can I install my project with npm?

**Comment by Cristian006** [comment]
No, not yet.. haven't had time to finish the project and add it to npm :/

**Comment by omerfeyyaz** [comment]
How do I add to my project?

**Comment by Cristian006** [comment]
I need to separate the component from the example project and upload it to npm, all you need is this folder: https://github.com/Cristian006/electron-titlebar/tree/master/app/components/TitleBar

**Comment by lazorfuzz** [comment]
@omerfeyyaz take a look at my fork:

https://github.com/lazorfuzz/electron-titlebar/

It's the same project except converted to an importable react library. For now, just git clone it, add it to your project folder, and import it relatively. I made a pull request to @Cristian006 so he can eventually publish it to npm.

**Comment by Cristian006** [comment]
@omerfeyyaz you can now install it from npm 👍
```
npm install frameless-titlebar
```
