### ISSUE TITLE
Double click on menu will get error 'getDisplayNearestPoint' of undefined

### ISSUE THREAD

**Issue by zenith6495** [Cristian006/frameless-titlebar#52]
![image](https://user-images.githubusercontent.com/37361993/76856504-60fc1780-688e-11ea-882a-7d8f5f86b756.png)

Whenever I double click on the menu, it will lead to this error. I tried to hide the menu as solution, however there is a small div portion of the menu will always be there (beside the app title), when you double click there will get this error as well. The frameless-titlebar example app don't have this issue though.

**Comment by Cristian006** [comment]
@zenith6495 just updated the project please try v2 :)
