### ISSUE TITLE
Make accessibility shortcuts optional 

### ISSUE THREAD

**Issue by bjorn-nesby** [Cristian006/frameless-titlebar#65]
I would love to update to the 2x version, however the addition of accessibility shortcuts effectively prevents me from doing this. 

The problem is that they will consume any existing shortcuts in my application that happens to be using the alt modifier as well. 

I guess the easiest solution by far is to have a flag that specifies whether the accessibility shortcuts are registered or not. 

The next solution I can think of will allow my application to process key events after they have been handled by this component. E.g. to allow a relatively common shortcut such as alt+arrow key to coexist with this menu (I would personally prefer this solution).    

I could open a PR for but would like to hear your opinion first. 
Thanks!

**Comment by Cristian006** [comment]
@bjorn-nesby please do 👍 haven't had too much time to work on this recently.
