### ISSUE TITLE
accelerator option not working

### ISSUE THREAD

**Issue by caesar3x** [Cristian006/frameless-titlebar#80]
**Describe the bug**
In my app, the menu show up. I have a menu item with configuration: accelerator: 'CmdOrCtrl+S',
When I press "Ctrl+S" on Windows, nothing happens. The menu works fine if I click on it.

Is it a bug or what I need to do to make the accelerator keys combination work?

**Comment by Cristian006** [comment]
@tuandt  Frameless Titlebar currently does not add these listeners automatically :(

This should be handled by the application by either adding an on key pressed listener to the document or another option might be using electron's [global shortcut](https://www.electronjs.org/docs/api/global-shortcut) feature 👍

**Comment by caesar3x** [comment]
Thank you very much for your reply and your great module also.
Hope that you can add this feature in near future.
